### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by SmackTO** [rkaczorek/astroberry-amh#2]
I'm having the following dependency issue when trying to compile for Ubuntu-MATE on RPi 3 B+:

`Scanning dependencies of target indi_amh_focuser
[ 90%] Building CXX object CMakeFiles/indi_amh_focuser.dir/amh_focuser.o
/home/steve/astroberry-amh/amh_focuser.cpp: In constructor ‘IndiAMHFocuser::IndiAMHFocuser()’:
/home/steve/astroberry-amh/amh_focuser.cpp:79:38: error: ‘setFocuserConnection’ was not declared in this scope
  setFocuserConnection(CONNECTION_NONE);
                                      ^
/home/steve/astroberry-amh/amh_focuser.cpp: In member function ‘virtual bool IndiAMHFocuser::initProperties()’:
/home/steve/astroberry-amh/amh_focuser.cpp:161:66: error: ‘SetFocuserCapability’ was not declared in this scope
  SetFocuserCapability(FOCUSER_CAN_ABS_MOVE | FOCUSER_CAN_REL_MOVE);
                                                                  ^
CMakeFiles/indi_amh_focuser.dir/build.make:62: recipe for target 'CMakeFiles/indi_amh_focuser.dir/amh_focuser.o' failed
make[2]: *** [CMakeFiles/indi_amh_focuser.dir/amh_focuser.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/indi_amh_focuser.dir/all' failed
make[1]: *** [CMakeFiles/indi_amh_focuser.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by rkaczorek** [comment]
The issue has been hotfixed in the last commit. The root cause is focuser properties changed in INDI libs, so sync was required in the driver's source code
