### ISSUE TITLE
AdafruitMotorHAT.h  not found during make

### ISSUE THREAD

**Issue by Fire-Power** [rkaczorek/astroberry-amh#3]
`pi@pi4:~/astroberry-amh/build$ make
Scanning dependencies of target indi_amh_focuser
[ 50%] Building CXX object CMakeFiles/indi_amh_focuser.dir/amh_focuser.o
In file included from /home/pi/astroberry-amh/amh_focuser.cpp:26:
/home/pi/astroberry-amh/amh_focuser.h:22:10: fatal error: Adafruit_MotorHAT.h: No such file or directory
 #include "Adafruit_MotorHAT.h"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/indi_amh_focuser.dir/build.make:63: CMakeFiles/indi_amh_focuser.dir/amh_focuser.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/indi_amh_focuser.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`
Is this problem just as simple as the file missing please ?

**Comment by rkaczorek** [comment]
Some changes were commited recently. Are you sure you have the latest sources?

**Comment by Fire-Power** [comment]
Hi 
I did the clone from here using the instructions on the readme.
I could not see the missing file on the Code page list of files.

**Comment by rkaczorek** [comment]
Fixed just now
